version: "3.9"
services:
  dev-container:
    build:
      dockerfile: ./.devcontainer/Dockerfile
      context: ./
    volumes:
      - .:/workspaces/mission-to-mars:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
